# Generated by Django 5.1.3 on 2024-11-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='produtos/default.jpg', upload_to='produtos/'),
        ),
        migrations.DeleteModel(
            name='ImagemProduto',
        ),
    ]
